### ISSUE TITLE
顶部tab页签切换bug

### ISSUE THREAD

**Issue by sjkmuninj** [click33/sa-admin#1]
点击向右滑动更多tab页签按钮之后tab页签位置出现位置异常

**Comment by click33** [comment]
这一块我也注意到了，这一部分实现时算法有点问题，回头我想到更好的算法后就把这块重写一下------------------ 原始邮件 ------------------
发件人: "张三"<notifications@github.com>
发送时间: 2019年5月16日(星期四) 上午9:17
收件人: "shengzhang666/sa-admin"<sa-admin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [shengzhang666/sa-admin] 顶部tab页签切换bug (#1)



点击向右滑动更多tab页签按钮之后tab页签位置出现位置异常
 
&mdash;

**Comment by click33** [comment]
此bug已修复
