### ISSUE TITLE
当动画效果是淡入的时候，开启多个标签，只有最后一个能滚动

### ISSUE THREAD

**Issue by wupeitao88888** [click33/sa-admin#2]
当动画效果是淡入的时候，开启多个标签，只有最后一个能上下滚动，其他都不能滚动，没有滚动条，我的电脑是Mac ，浏览器是chrome,不知道为什么？请大神解惑

**Comment by click33** [comment]
由于我身边暂时没有Mac电脑，无法复现此bug，可能要等到我有Mac时才能解决这个问题，你可以f12一下看看控制台有没有报错信息 ，提供一下，也许我看到报错信息就能将这个bug解决
